### ISSUE TITLE
ROM tests are not passing on travis CI for postgres and mysql

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#303]
https://travis-ci.org/RailsEventStore/rails_event_store/builds/367754123?utm_source=slack&utm_medium=notification

**Comment by paneq** [comment]
```
     Failure/Error: expect(rom_db.connection.pool.size).to eq(5)
     
       expected: 5
            got: 1
```

@joelvh Do you know what's the culprit? should I provide a different `DATABASE_URL` for travis? code in: #302

**Comment by joelvh** [comment]
@paneq fixed in #304

**Comment by joelvh** [comment]
@paneq I think we can close this issue

**Comment by paneq** [comment]
As far as I am aware we are still not testing rom on postgres and mysql on `master` branch on CI.

**Comment by paneq** [comment]
Will be closed when #302 issues are addressed
